apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: spot-cluster
  region: us-east-1 
  version: "1.36"   
iam:
  vpcResourceControllerPolicy: true
  withOIDC: true
accessConfig:
  authenticationMode: API_AND_CONFIG_MAP
managedNodeGroups:
  - name: spot-cluster-ng
    spot: true
    instanceTypes:
      - t2.large
      - t3.large
      - t3a.large
    desiredCapacity: 2
    maxSize: 3
    minSize: 2
    volumeSize: 30
    privateNetworking: true
    ssh:
      allow: false
    iam:
      withAddonPolicies:
        albIngress: true
        awsLoadBalancerController: true
        externalDNS: true
        imageBuilder: true